name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64]
        system: [server, client]
        exclude:
          - os: macos-latest
            system: server
          - os: ubuntu-latest
            system: client

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: ls
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            ls -al $HOME/bin
          fi

      - name: Test
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            os="linux"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            os="darwin"
          else
            echo "$RUNNER_OS not supported"
              exit 1
          fi
          
          DOTPATH=$(pwd) go test -cover -tags "$os",${{ matrix.arch }},${{ matrix.system }} -v ./...
