name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu20.04, macos-latest]
        arch: [amd64]
        system: [server, client]
        exclude:
          - os: macos-latest
            system: server

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        env: 
          DOTPATH: $(pwd)
        run: go test -tags ${{ matrix.os }},${{ matrix.arch }},${{ matrix.system }} -v ./...
